services:
  - type: web
    name: CoreAPI
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: mongodb://<seu-usuario>:<sua-senha>@<seu-servidor>:27017
      - key: JWT_SECRET
        value: sua_chave_secreta_aqui
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
